### ISSUE TITLE
[BUG] 最新action版本问题依旧存在！

### ISSUE THREAD

**Issue by johin528** [asdlokj1qpi23/subconverter#1]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

最新action

### 转换过程

v2 board机场订阅转换sing-box

### 转换设置

https://web.fscloud.cc/api/v1/client/subscribe?token=b17026fc7e48561ea105a30f80cb1853

### 复现步骤

![Screenshot_20231222_141608](https://github.com/asdlokj1qpi23/subconverter/assets/81177778/782e426d-385e-409d-9a79-437cb56e9c97)
![Screenshot_20231222_141555](https://github.com/asdlokj1qpi23/subconverter/assets/81177778/9adc0991-2a34-4f61-84d2-0095db514251)
报错日志如上，现在解析订阅配置虽说没有问题，outbound块依旧有问题，hy2和vless均没办法联通，已提供订阅链接！

### 期望结果

解决bug

### 实际结果

感谢作者！

### 错误信息

```shell
感谢作者！
```

**Comment by johin528** [comment]
我使用的是谷歌商店版本，1.7.6，日志一直提示reality vercation failed

**Comment by johin528** [comment]
使用的订阅转换网站为：
https://suburl.v1.mk

**Comment by johin528** [comment]
后端已经采用了本项目最新的action

**Comment by johin528** [comment]
貌似是某些参数导致的失败

https://api.v1.mk/sub?target=singbox&url=https%3A%2F%2F9981.mcwy.xyz%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D594a890e5431ae2d855ce97d1b71ae86&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false

**Comment by johin528** [comment]
scv必须要为true才可以？

**Comment by johin528** [comment]
经过测试，scv设置为true，hy2生效，但是vless一直不可以联通

这是官方的配置，他们的默认配置可以联通
https://web.fscloud.cc/api/v1/client/subscribe?token=b17026fc7e48561ea105a30f80cb1853&flag=sing-box

**Comment by johin528** [comment]
> The Singbox version 1.7.6 has also passed the test successfully.

我给你发的链接是原版链接，当然没问题，出问题是经过0.9.0最新action版订阅转换后，

**Comment by johin528** [comment]
> 经过测试，scv只有设置为true，hy2才生效，但是vless一直不可以联通，vless的short_id字段貌似缺失，packet_encoding字段不存在（xudp设置为true了），然后就是转换前reality属性在tls对象内，转换后reality属性被弄到了utls对象内
> 
> 这是官方的配置，他们的默认配置可以联通 https://web.fscloud.cc/api/v1/client/subscribe?token=b17026fc7e48561ea105a30f80cb1853&flag=sing-box

这里是详细的测试结果，相对原未转换前的链接

**Comment by youshandefeiyang** [comment]
yeah,it has been solved

**Comment by youshandefeiyang** [comment]
yeah,it has been solved

**Comment by johin528** [comment]
thanks a lot ,it has been solved.
